'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {TraceChart} from './charts';
import {RecordDetails,statusText} from './panels';
import {fmt,resultOf,textValue,type Defaults,type JsonRecord,type Optimization,type Result} from './types';
export function OptimizationPanel({defaults,result,onRun,onInspect,busy}:{defaults:Defaults;result:Optimization|null;onRun:(search:JsonRecord)=>void;onInspect:(analysisId:string)=>void;busy:boolean}) {
 const [search,setSearch]=useState<JsonRecord>(defaults.optimization_defaults??{});
 useEffect(()=>setSearch(defaults.optimization_defaults??{}),[defaults]);
 const variables=(search.variables??{}) as Record<string,number[]>;
 const best=resultOf(result?.best),base=resultOf(result?.baseline);
 const objectiveKey=String(result?.problem.objective??search.objective??'');
 const unit='kg',objectiveLabel=objectiveKey==='fuel_loaded_kg'?'任务装油':'起始质量';
 const objective=(r:Result|null)=>objectiveKey==='fuel_loaded_kg'?r?.fuel_loaded_kg:r?.mass?.mass_kg;
 const [all,setAll]=useState(false);
 const candidates=all?result?.candidates:result?.candidates?.slice(-12);
 return <><article className="panel search-panel"><div className="panel-title"><div><span className="eyebrow">外层 · 固定任务搜索</span><h3>在声明范围内选一个候选</h3></div><span className="status warning">沙盒问题 · 默认值待确认</span></div><p className="muted">本次任务、载荷工况、模型与求解配置在搜索期间冻结。每个候选都调用同一分析器；小网格与坐标搜索保留各自评价记录。</p><div className="search-settings"><label>演示目标<Select value={String(search.objective??'takeoff_mass_kg')} onValueChange={value=>setSearch(v=>({...v,objective:value}))}><SelectTrigger aria-label="优化目标"><SelectValue>{search.objective==='fuel_loaded_kg'?'降低任务装油':'降低起始质量'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="takeoff_mass_kg">降低起始质量</SelectItem><SelectItem value="fuel_loaded_kg">降低任务装油</SelectItem></SelectContent></Select></label>{['grid_levels','search_budget','max_rounds','seed'].map(key=><label key={key}>{({grid_levels:'每轴网格点',search_budget:'搜索评价预算',max_rounds:'最多轮次',seed:'随机种子'})[key]}<Input aria-label={key} type="number" min={key==='seed'?0:1} step="1" value={Number(search[key]??0)} onChange={e=>setSearch(v=>({...v,[key]:Number(e.target.value)}))}/></label>)}</div><Table><TableHeader><TableRow><TableHead>设计变量</TableHead><TableHead>搜索下界</TableHead><TableHead>搜索上界</TableHead><TableHead>单位</TableHead></TableRow></TableHeader><TableBody>{Object.entries(variables).map(([key,range])=>{const s=defaults.schema.inputs?.[key];return <TableRow key={key}><TableCell>{s?.label??key}</TableCell>{[0,1].map(i=><TableCell key={i}><Input aria-label={`${s?.label??key}${i?'上界':'下界'}`} type="number" min={s?.min} max={s?.max} step={s?.step} value={range[i]} onChange={e=>setSearch(v=>({...v,variables:{...variables,[key]:range.map((n,j)=>i===j?Number(e.target.value):n)}}))}/></TableCell>)}<TableCell>{s?.unit}</TableCell></TableRow>;})}</TableBody></Table><div className="search-actions"><Button disabled={busy} onClick={()=>onRun(search)}>{busy?'正在评价候选；保留各次失败…':'运行有限范围优化'}</Button><span className="muted">M03：使用现有几何作为 seed，明确跳过任务尺寸反求。</span></div><RecordDetails title="完整算法设置" value={search}/></article>
 {result&&<><article className="panel"><div className="panel-title"><div><span className="eyebrow">候选选择结果</span><h3>{best?'为什么选中这架候选':'本次没有找到可行候选'}</h3></div><span className={`status ${best?'limited':'warning'}`}>{best?'仅在当前模型与范围内':'证据不足或约束未满足'}</span></div><p>{textValue(result.selection?.reason)}</p><div className="metric-row"><div className="metric"><span>基线{objectiveLabel}</span><strong>{fmt(objective(base))}<small>{unit}</small></strong></div><div className="metric"><span>选中{objectiveLabel}</span><strong>{fmt(objective(best))}<small>{unit}</small></strong></div><div className="metric"><span>已记录候选</span><strong>{result.candidates?.length??0}</strong></div><div className="metric"><span>搜索评价 / 预算</span><strong>{String(result.search?.evaluations??'—')}<small>/ {String(result.search?.budget??'—')}</small></strong></div></div><dl><div><dt>停止原因</dt><dd>{textValue(result.search?.stop_reason)}</dd></div><div><dt>搜索相关最紧约束</dt><dd>{textValue((result.selection?.search_limiting_constraint as JsonRecord)?.name??(result.selection?.closest_constraint as JsonRecord)?.name??'见逐项约束')}</dd></div><div><dt>固定条件已贴边</dt><dd>{Array.isArray(result.selection?.fixed_active_constraints)?result.selection.fixed_active_constraints.map(c=>String((c as JsonRecord).name??'')).join('、')||'无':'见完整记录'}</dd></div><div><dt>碰到变量边界</dt><dd>{Array.isArray(result.selection?.boundary_hits)&&result.selection.boundary_hits.length?result.selection.boundary_hits.map(key=>defaults.schema.inputs?.[String(key)]?.label??String(key)).join('、'):'无'}</dd></div><div><dt>独立复核</dt><dd>未执行；候选未成为已验证飞机</dd></div></dl><p className="muted">停止搜索不证明全局最优。低阶模型之外的失速、屈曲、扭转及中央舱强度尚未覆盖。</p><TraceChart points={result.candidates.map((c,i)=>({x:c.index??i+1,y:typeof c.objective==='number'?c.objective:null}))} xLabel="候选评价编号" yLabel={`${objectiveLabel} / kg`}/><RecordDetails title="冻结的问题、seed 与选择依据" value={{problem:result.problem,seed:result.seed,selection:result.selection}}/><RecordDetails title="小网格对照与独立复核状态" value={{grid_reference:result.grid_reference,independent_review:result.independent_review}}/></article>
 <article className="panel"><div className="panel-title"><h3>每次候选留下的记录</h3><Button variant="outline" onClick={()=>setAll(v=>!v)}>{all?'仅看最近 12 次':'显示全部候选'}</Button></div><p className="muted">点击分析记录可查看那一次的三维设计、模块输入输出与约束来源。缺模型或求解失败的候选不伪造目标值。</p><Table><TableHeader><TableRow><TableHead>编号 / 方法</TableHead><TableHead>分析记录</TableHead><TableHead>状态</TableHead><TableHead>{objectiveLabel} / kg</TableHead><TableHead>最紧约束 / 失败</TableHead></TableRow></TableHeader><TableBody>{candidates?.map((c,i)=><TableRow key={c.analysis_id??i}><TableCell>{c.index??i+1} · {String(c.origin??'')}</TableCell><TableCell><button className="text-button mono" onClick={()=>c.analysis_id&&onInspect(c.analysis_id)}>{c.analysis_id?.slice(0,18)??'无记录'}</button></TableCell><TableCell><span className={`status ${c.evaluation_status==='feasible'?'limited':c.evaluation_status==='infeasible'?'bad':'warning'}`}>{statusText(c.evaluation_status??c.status??'unknown')}</span></TableCell><TableCell>{fmt(c.objective as number)}</TableCell><TableCell>{String(c.failure??(c.tightest_constraint as JsonRecord)?.name??'—')}</TableCell></TableRow>)}</TableBody></Table></article></>}
 </>;
}
