'use client';
import {useCallback,useEffect,useState} from 'react';
import {Download,Play,RotateCcw,AlertTriangle,ExternalLink} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {ControlledFields} from './controls';
import {TraceChart} from './charts';
import {ModulePanel,Evidence,ConstraintPanel,Comparison,RecordDetails,statusText} from './panels';
import {NativeCoefficients} from './native-coefficients';
import {OptimizationPanel} from './optimization';
import {Viewer3D} from './viewer3d';
import {activeConstraint,fmt,resultOf,type Config,type Defaults,type Inputs,type JsonRecord,type Optimization,type Result} from './types';
export type {Result} from './types';
const API='http://127.0.0.1:8842';
const failures:Record<string,string>={insufficient_power:'推进功率不足',trim_outside_demo_bounds:'超出攻角 / 舵偏范围',fuel_exhausted:'本次尝试的装油量耗尽',fuel_capacity_exceeded:'需油量超过容量',static_stability_not_supported:'该状态不满足演示静稳定条件',coupling_not_converged:'内层未收敛',descent_needs_extra_drag:'下降需要额外阻力模型',fuel_bracket_not_found:'未找到有效燃油括区；证据不足',no_valid_bracket:'未找到有效燃油括区；证据不足'};
const groupNames:Record<string,string>={aero:'气动假设',propulsion:'推进假设',structure:'结构与材料',constraints:'演示约束',geometry:'几何与空间',mass:'硬件质量',mission:'任务假设',load_case:'载荷工况',numerics:'数值设置'};

export default function Home(){
 const [defaults,setDefaults]=useState<Defaults|null>(null),[form,setForm]=useState<Inputs>({}),[model,setModel]=useState<Config>({}),[solver,setSolver]=useState<Config>({});
 const [r,setResult]=useState<Result|null>(null),[baseline,setBaseline]=useState<Result|null>(null),[optimization,setOptimization]=useState<Optimization|null>(null);
 const [busy,setBusy]=useState(false),[activity,setActivity]=useState(''),[error,setError]=useState(''),[mode,setMode]=useState('engineering'),[tab,setTab]=useState('calculation');
 const run=useCallback(async(inputs:Inputs,modelConfig:Config,solverConfig:Config)=>{
  setBusy(true);setActivity('正在搜索有效燃油括区并完成候选分析…');setError('');
  try{const response=await fetch(`${API}/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inputs,model_config:modelConfig,solver_config:solverConfig})});const next=await response.json() as Result & {error?:string};if(!response.ok)throw Error(next.error??'计算请求失败');setResult(next);setBaseline(prev=>prev??(next.status==='demo_converged'?next:null));}
  catch(e){setError(e instanceof Error?e.message:'计算服务不可用');}finally{setBusy(false);setActivity('');}
 },[]);
 useEffect(()=>{let alive=true;fetch(`${API}/defaults`).then(async response=>{if(!response.ok)throw Error('无法读取计算配置');return response.json() as Promise<Defaults>;}).then((data:Defaults)=>{if(!alive)return;setDefaults(data);setForm(data.inputs);setModel(data.model_config);setSolver(data.solver_config);void run(data.inputs,data.model_config,data.solver_config);}).catch(e=>{if(alive)setError(String(e));});return()=>{alive=false;};},[run]);
 async function optimize(search:JsonRecord){setBusy(true);setActivity('外层搜索运行中：逐一求解网格和搜索候选，等待完整评价记录…');setError('');try{const response=await fetch(`${API}/optimize`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inputs:form,model_config:model,solver_config:solver,search})});const next=await response.json() as Optimization&{error?:string};if(!response.ok)throw Error(next.error??'优化请求失败');setOptimization(next);const selected=resultOf(next.best);if(selected){setResult(selected);setForm(selected.inputs);}const base=resultOf(next.baseline);if(base)setBaseline(base);}catch(e){setError(e instanceof Error?e.message:'搜索失败');}finally{setBusy(false);setActivity('');}}
 async function inspect(analysisId:string){setBusy(true);setError('');try{const response=await fetch(`${API}/analyses/${encodeURIComponent(analysisId)}`);const next=await response.json() as Result & {error?:string};if(!response.ok)throw Error(next.error??'分析记录不存在');setResult(next);setForm(next.inputs);if(next.configuration){setModel(next.configuration.model);setSolver(next.configuration.solver);}setTab('calculation');window.scrollTo({top:0,behavior:'smooth'});}catch(e){setError(String(e));}finally{setBusy(false);}}
 function download(){const value=tab==='optimization'&&optimization?optimization:r;if(!value)return;const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=tab==='optimization'&&optimization?`bwb-search-${resultOf(optimization.best)?.analysis_id??'no-candidate'}.json`:`bwb-${r?.analysis_id??r?.analysis_hash??'analysis'}.json`;a.click();URL.revokeObjectURL(url);}
 const dirty=r&&(JSON.stringify(form)!==JSON.stringify(r.inputs)||JSON.stringify(model)!==JSON.stringify(r.configuration?.model)||JSON.stringify(solver)!==JSON.stringify(r.configuration?.solver));
 const tightest=r?activeConstraint(r):undefined,converged=r?.numeric_convergence==='converged';
 const fieldsFor=(group:string)=>Object.fromEntries(Object.entries(defaults?.schema.inputs??{}).filter(([,s])=>s.group===group));
 const updateInput=(key:string,value:number|string)=>setForm(v=>({...v,[key]:Number(value)}));
 const modelGroups=[...new Set(Object.values(defaults?.schema.model_config??{}).map(s=>s.group??'model'))];
 const solverTolerance=Number(r?.configuration?.solver.fuel_tolerance_kg??0);
 return <main><header className="topbar"><div className="brand"><span className="brand-mark">B</span><div><h1>BWB 候选设计工作台</h1><p>统一模型 · 固定任务分析 · 有限范围搜索</p></div></div><div className="header-actions"><span className="scope">本地独立演示</span><Button variant="outline" onClick={download} disabled={!r||mode!=='engineering'}><Download/>导出本次记录</Button></div></header><div className="mode-bar"><Tabs value={mode} onValueChange={value=>setMode(String(value))}><TabsList variant="line"><TabsTrigger value="engineering">低阶工程模型 · 整条演示链</TabsTrigger><TabsTrigger value="mit">MIT 资源 · 原生系数分析</TabsTrigger></TabsList></Tabs><span>两种模式明确保留各自能力边界</span></div>
 {mode==='mit'?<NativeCoefficients api={API}/>:<div className="workspace"><aside className="inputs"><div className="section-heading"><span>本次输入</span><Button variant="ghost" disabled={!defaults||busy} onClick={()=>{if(defaults){setForm(defaults.inputs);setModel(defaults.model_config);setSolver(defaults.solver_config);}}}><RotateCcw/>恢复</Button></div>{defaults?<><h2>固定任务 r</h2><ControlledFields prefix="mission" values={form} schema={fieldsFor('mission')} onChange={updateInput} sliders/><h2>候选硬件 x</h2><ControlledFields prefix="design" values={form} schema={fieldsFor('design')} onChange={updateInput} sliders/><details><summary>载荷工况</summary><ControlledFields prefix="load" values={form} schema={fieldsFor('load_case')} onChange={updateInput}/></details><details className="model-settings"><summary>计算模型参数</summary><p className="muted">这些参数控制实际模型；点击运行后冻结到新记录。</p>{modelGroups.map(group=><details key={group}><summary>{groupNames[group]??group}</summary><ControlledFields prefix={`model-${group}`} values={model} schema={Object.fromEntries(Object.entries(defaults.schema.model_config??{}).filter(([,s])=>(s.group??'model')===group))} onChange={(key,value)=>setModel(v=>({...v,[key]:value}))}/></details>)}</details><details><summary>燃油求解与离散设置</summary><ControlledFields prefix="solver" values={solver} schema={defaults.schema.solver_config??{}} onChange={(key,value)=>setSolver(v=>({...v,[key]:value}))}/></details><div className="run-area"><Button className="run-button" disabled={busy} onClick={()=>void run(form,model,solver)}><Play/>{busy?'正在计算…':'分析当前候选'}</Button><Button variant="outline" className="run-button" disabled={busy} onClick={()=>setTab('optimization')}>进入固定任务优化</Button><p>额定载荷属于硬件；本次装载属于任务。结果保留各自标识。</p></div></>:<p className="muted">读取计算服务配置…</p>}</aside><section className="results"><div className="notice"><AlertTriangle/><span>当前模型只覆盖声明的低阶物理。外翼弯曲可计算；独立飞机验证尚未执行。</span></div>{error&&<div className="error" role="alert">{error}</div>}{activity&&<div className="activity" role="status"><span className="busy-dot"/>{activity}</div>}{dirty&&<div className="changed">输入或配置已修改。下方保留之前的分析记录，运行后才会更新。</div>}
 {r?<><div className="result-heading"><div><span className="eyebrow">当前显示的分析 · {r.analysis_id??r.analysis_hash}</span><h2>{r.status==='demo_converged'?'一个有可追溯依据的候选':r.mission?'部分分析已完成，后续仍有缺口':'当前候选尚未获得有效分析'}</h2></div><span className={`status ${r.evaluation_status==='feasible'?'limited':r.evaluation_status==='infeasible'?'bad':'warning'}`}>{statusText(r.evaluation_status??'unknown')}</span></div>
 <div className="state-layers"><div><span>模型</span><strong>{r.model_metadata?.id??'未记录'}</strong><small>{r.model_metadata?.domain_check_status??'低阶演示域'}</small></div><div><span>数值求解</span><strong>{converged?'内层已收敛':'尚未完成'}</strong><small>燃油残差 {r.fuel_residual_kg?.toExponential(2)??'—'} kg</small></div><div className={r.evaluation_status==='infeasible'?'state-bad':''}><span>演示约束</span><strong>{statusText(r.evaluation_status??'unknown')}</strong><small>{tightest?`最紧：${tightest.name}`:'有效评价不足'}</small></div><div className="state-pending"><span>独立证据</span><strong>未执行</strong><small>不等于已验证飞机</small></div></div>
 {r.failure&&<div className="error"><strong>{failures[r.failure]??r.failure}</strong><RecordDetails title="失败阶段、工况和已保留的尝试" value={r.failure_details??r.fuel_solver}/></div>}
 <div className="metric-row">{[['起始质量',fmt(r.mass?.mass_kg),'kg'],['任务装油',fmt(r.fuel_loaded_kg),'kg'],['外翼弯曲应力',fmt(r.structure?.max_stress_MPa),'MPa'],['最小归一化余量',fmt(tightest?.normalized_margin,4),'']].map(([a,b,c])=><div className="metric" key={a}><span>{a}</span><strong>{b}<small>{c}</small></strong></div>)}</div>
 <Tabs value={tab} onValueChange={value=>setTab(String(value))} className="main-tabs"><TabsList variant="line"><TabsTrigger value="calculation">分析与三维</TabsTrigger><TabsTrigger value="optimization">固定任务优化</TabsTrigger><TabsTrigger value="flow">实际流程</TabsTrigger><TabsTrigger value="evidence">模型与证据</TabsTrigger></TabsList>
 <TabsContent value="calculation"><Viewer3D r={r}/><ConstraintPanel r={r}/><article className="panel"><div className="panel-title"><div><span className="eyebrow">内层 · 固定硬件求状态</span><h3>燃油可评价区间与闭合</h3></div><span>{r.iterations?.length??0} 次评价记录</span></div><TraceChart points={(r.iterations??[]).map(i=>({x:i.evaluation??i.iteration,y:i.residual_kg}))} xLabel="实际评价编号" yLabel="残差 / kg" log tolerance={solverTolerance}/><dl className="residual-values"><div><dt>燃油残差</dt><dd>{r.fuel_residual_kg?.toExponential(2)??'—'} kg</dd></div><div><dt>升力平衡残差</dt><dd>{r.mission?.lift_residual_N?.toExponential(2)??'—'} N</dd></div><div><dt>配平力矩残差</dt><dd>{r.mission?.moment_residual_Nm?.toExponential(2)??'—'} N·m</dd></div></dl><p className="muted">无效评价保留为空缺，不作为残差变号；数值收敛不会改变硬件厚度，也不代表外层已经找到最优。</p><RecordDetails title="所有燃油尝试与括区诊断" value={{solver:r.fuel_solver_diagnostics,attempts:r.iterations}}/></article><ModulePanel r={r}/><Comparison r={r} baseline={baseline} onPin={()=>setBaseline(r)}/></TabsContent>
 <TabsContent value="optimization">{defaults&&<OptimizationPanel defaults={defaults} result={optimization} onRun={search=>void optimize(search)} onInspect={id=>void inspect(id)} busy={busy}/>}</TabsContent>
 <TabsContent value="flow">{[['工程总览','/bwb-engineering-pipeline.svg','固定任务、候选、内层分析、外层搜索与独立复核'],['固定候选的分析依赖','/bwb-analysis-coupling.svg','同一截面、实际载荷和燃油状态的执行依赖']].map(([title,src,description])=><article className="panel flow-panel" key={src}><div className="panel-title"><div><h3>{title}</h3><p className="muted">{description}</p></div><a className="text-button" href={src} target="_blank" rel="noreferrer"><ExternalLink size={16}/>打开完整图</a></div><img className="flow-image" src={src} alt={description}/></article>)}<p className="muted">流程架构说明依赖关系；本次执行覆盖以“分析与三维”中的模块记录为准。独立复核与未来训练不表示已运行。</p></TabsContent>
 <TabsContent value="evidence"><Evidence r={r} defaults={defaults}/></TabsContent></Tabs></>:<div className="loading">读取模型与输入后，运行默认候选…</div>}</section></div>}
 </main>;
}
