'use client';
import {useState} from 'react';
import {fmt,MiniLine,type Result} from './page';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
const names:Record<string,string>={M01:'任务需求',M02:'问题定义',M03:'初步尺寸',M04:'几何布局',M05:'大气工况',M06:'气动配平',M07:'载荷传递',M08:'结构响应',M09:'质量重心',M10:'燃油任务',M11:'约束评价',M12:'独立复核'};
export function ModulePanel({r}:{r:Result}){
 const [active,setActive]=useState('M06');const p=r.mission?.trace.find(a=>a.phase==='cruise');
 const data:Record<string,[string,string,string,[string,string][]]>={
 M01:['任务 = 爬升 + 巡航航段 + 下降','高度、真空速与终点事件形成阶段表，送往工况和任务积分。','未模拟起飞、着陆及备降航迹。',[['载荷',`${fmt(r.inputs.payload_kg)} kg`],['巡航航段',`${fmt(r.inputs.cruise_km)} km`]]],
 M02:['min f(x,y), subject to g(x,y) ≤ 0','只建立任务和候选变量关系，本轮由您手动修改外层设计。','正式目标、边界和优化算法待老师确认；不自动寻找最优飞机。',[['目标','待老师确认'],['外层','手动修改设计']]],
 M03:['m₀ = m_structure + m_systems + m_payload + m_fuel','输入几何就是候选尺寸；以油箱容量作为首个燃油猜测，必要时以半容量重试。','尚未实现从任务反求翼面积的自动初步尺寸设计。',[['首个装油猜测',`${fmt(r.iterations[0]?.fuel_guess_kg)} kg`],['翼面积',`${fmt(r.geometry.area_m2)} m²`]]],
 M04:['S = 2∫c(y)dy; V ≈ 2∫0.6(t/c)c²dy','分段梯形几何精确积分；内部自由空间按演示比例分配，传给结构、油箱与质量账本。','体积代理未做舱室布尔运算或载荷包络装配。',[['MAC',`${fmt(r.geometry.mac_m)} m`],['载荷空间',`${fmt(r.geometry.payload_volume_m3,3)} m³`],['油箱体积',`${fmt(r.geometry.tank_volume_m3,3)} m³`]]],
 M05:['q = ½ρV²; Re = ρV·MAC/μ','对流层标准大气与Sutherland黏度；每个任务节点重新求动压和雷诺数。','演示输入是真空速；未将其当作KCAS。',[['巡航高度',`${fmt(r.inputs.altitude_m)} m`],['真空速',`${fmt(r.inputs.cruise_speed_ms)} m/s`]]],
 M06:['L = qS C_L; C_m,CG = 0; T = D + W sinγ','线性CL/Cm演示模型解2×2方程求攻角和升降副翼，再求匹配推力/功率；输入来自几何、工况和当前质量CG。','气动与舵偏响应是演示假设，未接MIT模型或进行独立气动验证。',[['巡航攻角',`${fmt(p?.alpha_deg)}°`],['副翼偏角',`${fmt(p?.elevon_deg)}°`],['配平L/D',fmt(p?.ld)]]],
 M07:['ΣF_node = ΣF_strip; ΣyF_node = ΣyF_strip','在示例拉起工况规定椭圆升力分布；条带力一半分给相邻节点，保持合力与展向一阶矩。','只处理垂向力及展向弯曲；完整压力、俯仰扭矩映射和6分量载荷仍缺。',[['合力映射误差',`${r.structure?.map_force_error_N.toExponential(2)??'—'} N`],['展向矩误差',`${r.structure?.map_span_moment_error_Nm.toExponential(2)??'—'} N·m`]]],
 M08:['EI w″ = M; σ = Mz/I','外翼根固定，净气动载荷减去结构惯性卸载；积分弯矩和曲率，给出应力、挠度和几何质量。','仅外翼线弹性弯曲；中央舱、扭转、屈曲、疲劳和连接强度未求解。',[['弯曲应力',`${fmt(r.structure?.max_stress_MPa)} MPa`],['翼端挠度',`${fmt(r.structure?.tip_deflection_m,4)} m`],['根弯矩',`${fmt(r.structure?.root_bending_Nm)} N·m`]]],
 M09:['m = Σmᵢ; x_CG = Σmᵢxᵢ / m','每节点按燃油更新结构、推进、系统、载荷、起落架和油箱账本，反馈给配平与任务。','示例部件位置与一个等效油箱；没有实测账本或多箱供油策略。',[['起始质量',`${fmt(r.mass?.mass_kg)} kg`],['起始CG',r.mass?`${fmt(r.mass.cg_mac*100)}% MAC`:'—'],['结构质量',`${fmt(r.geometry.structural_mass_kg)} kg`]]],
 M10:['P = TV/η; ṁ_f = BSFC·P/3600','每航段36步显式中点积分，每节点重算质量和配平；反求装油=消耗×1.15+1.5kg，松弛迭代至燃油残差≤10⁻⁴kg。','效率、耗油率、备份15%和不可用燃油1.5kg均为演示假设。',[['消耗燃油',`${fmt(r.mission?.burn_kg)} kg`],['三航段时间',`${fmt(r.mission?.duration_h)} h`],['含爬降总距离',`${fmt(r.mission?.total_distance_km)} km`]]],
 M11:['g_upper = calculated − limit','逐项比较容量、空间、外翼弯曲与功率；缺模型或数值失败时不报告可行。','120MPa、3%外翼长挠度等仅为演示判据。',[['演示检查',r.demo_constraints_satisfied?'满足':r.status==='unsupported'?'无有效评价':'有违约'],['工程可行性','未知']]],
 M12:['e = |prediction − independent reference|','导出候选输入、迭代与工况记录，为下一轮独立CFD/FEA或试验复核保留入口。','同一模型重复运行不能独立验证自己。',[['独立整机复核','未执行'],['置信区间','未提供']]]};
 const [equation,method,limit,values]=data[active];
 return <article className="panel"><div className="panel-title"><h3>沿着模块查看计算</h3><span>编号与流程图一致</span></div><div className="module-grid">{Object.entries(names).map(([id,name])=><button aria-pressed={active===id} className={active===id?'active':''} key={id} onClick={()=>setActive(id)}><small>{id}</small>{name}</button>)}</div><div className="module-detail"><div><span className="eyebrow">{active} · {['M02','M12'].includes(active)?'待完成':'演示计算 / 有限覆盖'}</span><h3>{names[active]}</h3><code>{equation}</code><p>{method}</p><p className="muted">覆盖边界：{limit}</p></div><dl>{values.map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div>{active==='M09'&&r.mass&&<Table><TableHeader><TableRow><TableHead>部件</TableHead><TableHead>质量 / kg</TableHead><TableHead>位置x / m（向后）</TableHead></TableRow></TableHeader><TableBody>{r.mass.components.map(c=><TableRow key={c.name}><TableCell>{c.name}</TableCell><TableCell>{fmt(c.mass_kg)}</TableCell><TableCell>{fmt(c.x_m,3)}</TableCell></TableRow>)}</TableBody></Table>}{active==='M10'&&r.mission&&<div className="trace-grid"><div><h3>剩余燃油 / kg</h3><MiniLine values={r.mission.trace.map(a=>a.fuel_kg)}/></div><div><h3>重心 / %MAC</h3><MiniLine values={r.mission.trace.map(a=>100*a.cg_mac)}/></div><Table><TableHeader><TableRow><TableHead>航段终点</TableHead><TableHead>时间/min</TableHead><TableHead>剩余燃油/kg</TableHead><TableHead>CG/%MAC</TableHead></TableRow></TableHeader><TableBody>{['climb','cruise','descent'].map((phase,i)=>{const end=r.mission!.trace.filter(a=>a.phase===phase).at(-1);return end?<TableRow key={phase}><TableCell>{['爬升','巡航','下降'][i]}</TableCell><TableCell>{fmt(end.time_s/60)}</TableCell><TableCell>{fmt(end.fuel_kg)}</TableCell><TableCell>{fmt(end.cg_mac*100)}</TableCell></TableRow>:null;})}</TableBody></Table></div>}{active==='M08'&&r.structure&&<div className="trace-grid"><div><h3>外翼弯曲应力 / MPa</h3><MiniLine values={r.structure.trace.map(a=>a.stress_MPa)}/></div><div><h3>外翼挠度 / m</h3><MiniLine values={r.structure.trace.map(a=>a.deflection_m)}/></div></div>}</article>;
}
const assumptionNames:Record<string,string>={cl0:'零攻角升力系数',cl_delta_per_rad:'舵偏升力斜率 / rad⁻¹',cm0:'参考俯仰矩系数',cm_alpha_per_rad:'攻角俯仰矩斜率 / rad⁻¹',cm_delta_per_rad:'舵偏俯仰矩斜率 / rad⁻¹',cd0:'零升阻力系数',oswald_e:'Oswald效率',propeller_efficiency:'螺桨效率',bsfc_kg_kwh:'耗油率 / kg·kWh⁻¹',material_E_Pa:'弹性模量 / Pa',material_density_kg_m3:'结构密度 / kg·m⁻³',fuel_density_kg_m3:'燃油密度 / kg·m⁻³',demo_stress_limit_MPa:'演示应力阈值 / MPa',demo_deflection_limit_fraction:'演示挠度/外翼长',usable_volume_fraction:'可用空间比例',payload_space_fraction:'载荷空间分配比例',required_payload_volume_m3:'示例载荷空间要求 / m³',reserve_fraction_of_burn:'备份燃油/消耗燃油',unusable_fuel_kg:'不可用燃油 / kg',climb_rate_ms:'爬升率 / m·s⁻¹',descent_rate_ms:'下降率 / m·s⁻¹',design_load_speed_ms:'载荷工况速度 / m·s⁻¹',design_load_altitude_m:'载荷工况高度 / m',alpha_bounds_deg:'演示攻角范围 / °',elevon_bounds_deg:'演示舵偏范围 / °'};
export function Evidence({r}:{r:Result}){return <><article className="panel"><h3>M11 · 本次演示检查</h3><p className="muted">以下是计算结果与演示判据，不能据此声明整机验证通过。</p><Table><TableHeader><TableRow><TableHead>项目</TableHead><TableHead>计算值</TableHead><TableHead>演示要求</TableHead><TableHead>结果</TableHead></TableRow></TableHeader><TableBody>{r.checks.map(c=><TableRow key={c.name}><TableCell>{c.name}</TableCell><TableCell>{fmt(c.value,3)} {c.unit}</TableCell><TableCell>{['载荷空间代理','最小功率余量'].includes(c.name)?'≥':'≤'} {fmt(c.limit,3)} {c.unit}</TableCell><TableCell>{c.pass_?'满足':'违约'}</TableCell></TableRow>)}</TableBody></Table>{!r.checks.length&&<p>本次没有可用于约束评价的有效完整结果。</p>}</article><article className="panel"><h3>C01 · 真实迭代记录</h3><p className="muted">固定几何 / 厚度 / 推进配置，只更新分析中的装油量；不在迭代中增厚结构。</p><Table><TableHeader><TableRow><TableHead>迭代</TableHead><TableHead>装油猜测/kg</TableHead><TableHead>本次需求/kg</TableHead><TableHead>闭合残差/kg</TableHead></TableRow></TableHeader><TableBody>{r.iterations.map((a,i)=><TableRow key={i}><TableCell>{a.iteration}</TableCell><TableCell>{fmt(a.fuel_guess_kg,4)}</TableCell><TableCell>{fmt(a.required_fuel_kg,4)}</TableCell><TableCell>{a.residual_kg===null?a.status:a.residual_kg.toExponential(3)}</TableCell></TableRow>)}</TableBody></Table></article><article className="panel"><h3>MIT资源、演示模型与独立证据</h3><p>已核查的 MIT 接口只直接返回 CL、CD、L/D。当前未提供可调用的配平控制响应或结构预测模型；本演示使用独立简化模型，未复制 MIT 数据或权重。</p><p>尚缺真实气动力矩/舵面响应、压力场和完整载荷映射、中央结构/扭转/屈曲、可信质量账本与推进图、独立整机复核。</p><p className="muted">测试记录在本地验证文件中。模型物理准确性、整机验证和优化算法均未通过演示测试获得证明。</p></article><article className="panel"><h3>本次使用的演示假设</h3><Table><TableHeader><TableRow><TableHead>参数</TableHead><TableHead>使用值</TableHead></TableRow></TableHeader><TableBody>{Object.entries(r.assumptions).map(([key,value])=><TableRow key={key}><TableCell>{assumptionNames[key]??key}</TableCell><TableCell>{Array.isArray(value)?value.join(' … '):value}</TableCell></TableRow>)}</TableBody></Table></article></>;}
