export type Inputs = Record<string, number>;
export type Config = Record<string, number|string>;
export type JsonRecord = Record<string, unknown>;
export type FieldSchema = {label?: string; title?: string; unit?: string; min?: number; max?: number; step?: number; group?: string; description?: string; role?: string; default?: number;choices?:string[]};
export type FieldMap = Record<string, FieldSchema>;
export type Schema = {inputs?: FieldMap; model_config?: FieldMap; solver_config?: FieldMap; [key:string]: unknown};
export type Defaults = {inputs: Inputs; bounds: Record<string, number[]>; model_config: Config; solver_config: Config; schema: Schema; modules?: ModuleRecord[]; optimization_defaults?: JsonRecord};
export type Section = {y_m:number; chord_m:number; leading_edge_x_m:number; corners:{x_m:number;z_m:number}[]; area_m2:number; I_m4:number; centroid_x_m:number; centroid_z_m:number; extreme_z_m:number; EI_Nm2:number; mass_per_length_kg_m:number};
export type Geometry = {area_m2:number;mac_m:number;xac_m:number;geometric_quarter_chord_x_m?:number;aspect_ratio:number;fuel_capacity_kg:number;payload_volume_m3:number;structural_mass_kg:number;gross_volume_m3:number;tank_volume_m3:number;stations:{y:number;c:number;x:number}[];section_layout?:{id:string;front_spar_u:number;rear_spar_u:number;thickness_ratio:number;wall_thickness_m:number;root_y_m:number;description?:string}; sections?:Section[];structural_components?:JsonRecord[]};
export type ModuleRecord = {id:string;name?:string;title?:string;status:string;inputs:unknown;outputs:unknown;formula:string|string[];method:string;limitation:string|string[];evidence?:unknown;[key:string]:unknown};
export type Constraint = {id?:string;name:string;value:number;limit:number;unit:string;sense?:string;g?:number;margin?:number;normalized_margin?:number;pass_:boolean;source?:{module?:string;condition_id?:string;state_id?:string;analysis_hash?:string;load_case_hash?:string;[key:string]:unknown}};
export type MissionPoint = {phase:string;time_s:number;condition_id?:string;state_id?:string;altitude_m:number;fuel_kg:number;alpha_deg:number;elevon_deg:number;ld:number;cg_mac:number;power_required_kw:number;mass_kg:number;[key:string]:unknown};
export type ModelMetadata = {id:string;version?:string;source_commit?:string;geometry_decoder_id?:string;supported_quantities?:string[];supported_inputs?:unknown;supported_load_cases?:unknown;validity_domain?:unknown;domain_check_status?:string;units?:unknown;axes?:unknown;S_ref?:unknown;length_ref?:unknown;moment_reference?:unknown;evidence_ids?:unknown;[key:string]:unknown};
export type Result = {inputs:Inputs;analysis_id?:string;analysis_hash?:string;design_hash:string;mission_hash?:string;load_case_hash?:string;config_hash?:string;comparability_hash?:string;status:string;evaluation_status?:string;failure?:string;failure_details?:JsonRecord;coverage:Record<string,string>;geometry:Geometry;iterations:{iteration:number;evaluation?:number;fuel_guess_kg:number;required_fuel_kg?:number;residual_kg:number|null;status:string;[key:string]:unknown}[];fuel_solver?:JsonRecord;fuel_loaded_kg?:number;fuel_residual_kg?:number;demo_constraints_satisfied?:boolean;mass?:{mass_kg:number;cg_mac:number;cg_x_m:number;components:{name:string;mass_kg:number;x_m:number}[]};mission?:{burn_kg:number;duration_h:number;total_distance_km:number;min_power_margin_kw:number;lift_residual_N:number;moment_residual_Nm:number;trace:MissionPoint[];[key:string]:unknown};structure?:{max_stress_MPa:number;tip_deflection_m:number;root_bending_Nm:number;map_force_error_N?:number;map_span_moment_error_Nm?:number;consumed_load_case_hash?:string;load_case?:JsonRecord;sections?:Section[];root_reaction_N?:number;trace:{y_m:number;stress_MPa:number;deflection_m:number;[key:string]:unknown}[];[key:string]:unknown};constraints?:Constraint[];checks:Constraint[];assumptions?:Record<string,number|number[]>;configuration?:{model:Config;solver:Config;hashes?:JsonRecord};model_metadata?:ModelMetadata;module_records?:ModuleRecord[];independent_review?:JsonRecord;[key:string]:unknown};
export type Candidate = {index?:number;candidate_id?:string;analysis_id?:string;inputs?:Inputs;design?:Inputs;status?:string;evaluation_status?:string;objective?:number|null;objective_value?:number|null;min_normalized_margin?:number;active_constraint?:unknown;analysis?:Result;result?:Result;[key:string]:unknown};
export type Optimization = {status:string;problem:JsonRecord;seed:unknown;baseline?:Result|Candidate;best?:Result|Candidate|null;candidates:Candidate[];grid_reference?:JsonRecord;search:JsonRecord;selection:JsonRecord;independent_review?:JsonRecord;[key:string]:unknown};

export const fmt=(n:number|undefined|null,d=2)=>typeof n!=='number'||!Number.isFinite(n)?'—':n.toLocaleString('en-US',{maximumFractionDigits:d,minimumFractionDigits:d});
export const textValue=(value:unknown):string=>value===null||value===undefined?'未提供':typeof value==='string'?value:typeof value==='number'?String(value):JSON.stringify(value,null,2);
export function resultOf(value:Result|Candidate|null|undefined):Result|null {if(!value)return null;if('geometry' in value)return value as Result;return value.analysis??value.result??null;}
export const checksOf=(r:Result)=>r.constraints??r.checks??[];
export const activeConstraint=(r:Result)=>checksOf(r).filter(c=>Number.isFinite(c.normalized_margin)).toSorted((a,b)=>a.normalized_margin!-b.normalized_margin!)[0];
export function comparisonDifferences(a:Result,b:Result):string[]{
 const fields:[keyof Result,string][]=[['mission_hash','任务'],['load_case_hash','载荷工况'],['config_hash','模型 / 求解配置']];
 const differences=fields.filter(([key])=>!a[key]||!b[key]||a[key]!==b[key]).map(([,label])=>label);
 if(a.model_metadata?.id!==b.model_metadata?.id||a.model_metadata?.version!==b.model_metadata?.version)differences.push('模型版本');
 if(a.comparability_hash&&b.comparability_hash)return a.comparability_hash===b.comparability_hash?[]:differences.length?differences:['比较条件'];
 return differences;
}
